// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
)

type Rendition struct {
	ID      int64
	VideoID string
	Label   string
	Bitrate int64
	Width   int64
	Height  int64
	Path    string
}

type Video struct {
	ID       string
	Filename string
	UploadAt string
	Duration sql.NullInt64
	Width    sql.NullInt64
	Height   sql.NullInt64
	Status   string
}
